"""Initial migration

Revision ID: 07ae0755f56f
Revises: 
Create Date: 2025-09-14 12:04:40.179550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07ae0755f56f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('oauth_provider', sa.String(length=50), nullable=False),
    sa.Column('oauth_subject_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_email'),
    sa.UniqueConstraint('oauth_provider', 'oauth_subject_id', name='uq_oauth_provider_subject')
    )
    op.create_index('ix_oauth_provider', 'users', ['oauth_provider', 'email'], unique=False)
    op.create_table('labels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_label_name')
    )
    op.create_index('ix_labels_user_id', 'labels', ['user_id'], unique=False)
    op.create_table('task_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('default_priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='prioritylevel'), nullable=False),
    sa.Column('recurrence_pattern', sa.String(length=50), nullable=False),
    sa.Column('recurrence_interval', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_templates_recurrence_pattern', 'task_templates', ['recurrence_pattern'], unique=False)
    op.create_index('ix_task_templates_user_id', 'task_templates', ['user_id'], unique=False)
    op.create_table('task_streaks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_completion_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['task_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'template_id', name='uq_user_template_streak')
    )
    op.create_index('ix_task_streaks_template_id', 'task_streaks', ['template_id'], unique=False)
    op.create_index('ix_task_streaks_user_id', 'task_streaks', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='prioritylevel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('time_spent', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['task_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'parent_id', 'order_index', name='uq_user_parent_order')
    )
    op.create_index('ix_parent_id', 'tasks', ['parent_id'], unique=False)
    op.create_index('ix_template_id', 'tasks', ['template_id'], unique=False)
    op.create_index('ix_user_id', 'tasks', ['user_id'], unique=False)
    op.create_index('ix_user_id_parent_id_order_index', 'tasks', ['user_id', 'parent_id', 'order_index'], unique=False)
    op.create_index('ix_user_id_scheduled_date', 'tasks', ['user_id', 'scheduled_date'], unique=False)
    op.create_index('ix_user_id_status', 'tasks', ['user_id', 'status'], unique=False)
    op.create_table('task_completions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('time_spent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['task_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_completions_completed_at', 'task_completions', ['completed_at'], unique=False)
    op.create_index('ix_task_completions_template_id', 'task_completions', ['template_id'], unique=False)
    op.create_index('ix_task_completions_user_id', 'task_completions', ['user_id'], unique=False)
    op.create_index('ix_task_completions_user_template_date', 'task_completions', ['user_id', 'template_id', 'completed_at'], unique=False)
    op.create_table('task_labels',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('label_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'label_id')
    )
    op.create_index('ix_task_labels_label_id', 'task_labels', ['label_id'], unique=False)
    op.create_index('ix_task_labels_task_id', 'task_labels', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_labels_task_id', table_name='task_labels')
    op.drop_index('ix_task_labels_label_id', table_name='task_labels')
    op.drop_table('task_labels')
    op.drop_index('ix_task_completions_user_template_date', table_name='task_completions')
    op.drop_index('ix_task_completions_user_id', table_name='task_completions')
    op.drop_index('ix_task_completions_template_id', table_name='task_completions')
    op.drop_index('ix_task_completions_completed_at', table_name='task_completions')
    op.drop_table('task_completions')
    op.drop_index('ix_user_id_status', table_name='tasks')
    op.drop_index('ix_user_id_scheduled_date', table_name='tasks')
    op.drop_index('ix_user_id_parent_id_order_index', table_name='tasks')
    op.drop_index('ix_user_id', table_name='tasks')
    op.drop_index('ix_template_id', table_name='tasks')
    op.drop_index('ix_parent_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_task_streaks_user_id', table_name='task_streaks')
    op.drop_index('ix_task_streaks_template_id', table_name='task_streaks')
    op.drop_table('task_streaks')
    op.drop_index('ix_task_templates_user_id', table_name='task_templates')
    op.drop_index('ix_task_templates_recurrence_pattern', table_name='task_templates')
    op.drop_table('task_templates')
    op.drop_index('ix_labels_user_id', table_name='labels')
    op.drop_table('labels')
    op.drop_index('ix_oauth_provider', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
