"""remove started_at from movies table

Revision ID: 09ce8d147243
Revises: e8b6334e3e05
Create Date: 2025-11-26 20:36:35.464684

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '09ce8d147243'
down_revision: Union[str, Sequence[str], None] = 'e8b6334e3e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'started_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('started_at', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
