"""Task archiving

Revision ID: 27ab2918ae1b
Revises: 6a59e0d8a5bc
Create Date: 2025-10-20 20:28:14.099147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27ab2918ae1b'
down_revision: Union[str, Sequence[str], None] = '6a59e0d8a5bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('archived', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('tasks', sa.Column('archived_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'archived_at')
    op.drop_column('tasks', 'archived')
    # ### end Alembic commands ###
