"""Add project

Revision ID: 48270e9259f2
Revises: 7e1299af8918
Create Date: 2025-10-16 22:57:02.642884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48270e9259f2'
down_revision: Union[str, Sequence[str], None] = '7e1299af8918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_user_id', 'projects', ['user_id'], unique=False)
    op.add_column('tasks', sa.Column('project_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_user_id'), table_name='tasks')
    op.create_index('ix_tasks_user_id', 'tasks', ['user_id'], unique=False)
    op.drop_constraint(op.f('tasks_parent_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tasks', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_parent_id_fkey'), 'tasks', 'tasks', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_tasks_user_id', table_name='tasks')
    op.create_index(op.f('ix_user_id'), 'tasks', ['user_id'], unique=False)
    op.drop_column('tasks', 'project_id')
    op.drop_index('ix_projects_user_id', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
