"""add priorities table and update task with priority_id and due_datetime

Revision ID: 49e99a5fc614
Revises: 1dedf57ba7d1
Create Date: 2025-10-22 19:46:40.466441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49e99a5fc614'
down_revision: Union[str, Sequence[str], None] = '1dedf57ba7d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priorities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_priorities_name', 'priorities', ['name'], unique=False)
    op.add_column('tasks', sa.Column('due_datetime', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('priority_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'priorities', ['priority_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'priority_id')
    op.drop_column('tasks', 'due_datetime')
    op.drop_index('ix_priorities_name', table_name='priorities')
    op.drop_table('priorities')
    # ### end Alembic commands ###
