"""add recurrence interval and unit fields

Revision ID: 5298cd44f707
Revises: 5c8b1bdc30ae
Create Date: 2025-11-15 20:16:02.678496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5298cd44f707'
down_revision: Union[str, Sequence[str], None] = '5c8b1bdc30ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('recurrence_interval', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('recurrence_unit', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###

    # Migrate existing recurrence_type values to new interval/unit system
    op.execute("""
        UPDATE tasks
        SET recurrence_interval = 1, recurrence_unit = 'days'
        WHERE recurrence_type = 'daily'
    """)

    op.execute("""
        UPDATE tasks
        SET recurrence_interval = 2, recurrence_unit = 'days'
        WHERE recurrence_type = 'alternate_days'
    """)

    op.execute("""
        UPDATE tasks
        SET recurrence_interval = 1, recurrence_unit = 'weeks'
        WHERE recurrence_type = 'weekly'
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'recurrence_unit')
    op.drop_column('tasks', 'recurrence_interval')
    # ### end Alembic commands ###
