"""Add is_inbox column to projects table

Revision ID: 5c8b1bdc30ae
Revises: eab170768b74
Create Date: 2025-11-15 15:37:42.315944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c8b1bdc30ae'
down_revision: Union[str, Sequence[str], None] = 'eab170768b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_inbox', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_inbox')
    # ### end Alembic commands ###
