"""add_genre_many_to_many_tables

Revision ID: 6120c9c434eb
Revises: b0aedba85e96
Create Date: 2025-11-21 19:13:40.433871

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6120c9c434eb'
down_revision: Union[str, Sequence[str], None] = 'b0aedba85e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _ = op.create_table('genres',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_genres_user_id_name')
    )
    op.create_index('ix_genres_user_id', 'genres', ['user_id'], unique=False)
    _ = op.create_table('book_genres',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('genre_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'genre_id')
    )
    op.create_index('ix_book_genres_book_id', 'book_genres', ['book_id'], unique=False)
    op.create_index('ix_book_genres_genre_id', 'book_genres', ['genre_id'], unique=False)
    _ = op.create_table('game_genres',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('genre_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'genre_id')
    )
    op.create_index('ix_game_genres_game_id', 'game_genres', ['game_id'], unique=False)
    op.create_index('ix_game_genres_genre_id', 'game_genres', ['genre_id'], unique=False)
    _ = op.create_table('manga_genres',
    sa.Column('manga_id', sa.Uuid(), nullable=False),
    sa.Column('genre_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('manga_id', 'genre_id')
    )
    op.create_index('ix_manga_genres_genre_id', 'manga_genres', ['genre_id'], unique=False)
    op.create_index('ix_manga_genres_manga_id', 'manga_genres', ['manga_id'], unique=False)
    _ = op.create_table('movie_genres',
    sa.Column('movie_id', sa.Uuid(), nullable=False),
    sa.Column('genre_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id')
    )
    op.create_index('ix_movie_genres_genre_id', 'movie_genres', ['genre_id'], unique=False)
    op.create_index('ix_movie_genres_movie_id', 'movie_genres', ['movie_id'], unique=False)
    _ = op.create_table('show_genres',
    sa.Column('show_id', sa.Uuid(), nullable=False),
    sa.Column('genre_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('show_id', 'genre_id')
    )
    op.create_index('ix_show_genres_genre_id', 'show_genres', ['genre_id'], unique=False)
    op.create_index('ix_show_genres_show_id', 'show_genres', ['show_id'], unique=False)
    op.add_column('books', sa.Column('is_audiobook', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('books', 'genre')
    op.drop_column('games', 'genre')
    op.drop_column('manga', 'genre')
    op.drop_column('movies', 'genre')
    op.drop_column('shows', 'genre')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('genre', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('genre', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('manga', sa.Column('genre', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('genre', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('genre', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('books', 'is_audiobook')
    op.drop_index('ix_show_genres_show_id', table_name='show_genres')
    op.drop_index('ix_show_genres_genre_id', table_name='show_genres')
    op.drop_table('show_genres')
    op.drop_index('ix_movie_genres_movie_id', table_name='movie_genres')
    op.drop_index('ix_movie_genres_genre_id', table_name='movie_genres')
    op.drop_table('movie_genres')
    op.drop_index('ix_manga_genres_manga_id', table_name='manga_genres')
    op.drop_index('ix_manga_genres_genre_id', table_name='manga_genres')
    op.drop_table('manga_genres')
    op.drop_index('ix_game_genres_genre_id', table_name='game_genres')
    op.drop_index('ix_game_genres_game_id', table_name='game_genres')
    op.drop_table('game_genres')
    op.drop_index('ix_book_genres_genre_id', table_name='book_genres')
    op.drop_index('ix_book_genres_book_id', table_name='book_genres')
    op.drop_table('book_genres')
    op.drop_index('ix_genres_user_id', table_name='genres')
    op.drop_table('genres')
    # ### end Alembic commands ###
