"""Add order_idx to task

Revision ID: 6a59e0d8a5bc
Revises: afebb179081d
Create Date: 2025-10-20 19:21:16.735872

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6a59e0d8a5bc'
down_revision: Union[str, Sequence[str], None] = 'afebb179081d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('order_index', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'order_index')
    # ### end Alembic commands ###
