"""Add parent id

Revision ID: 7e1299af8918
Revises: 1fb94fa770c0
Create Date: 2025-10-16 22:21:12.473904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e1299af8918'
down_revision: Union[str, Sequence[str], None] = '1fb94fa770c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('parent_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.create_index('ix_user_id', 'tasks', ['user_id'], unique=False)
    op.drop_constraint(op.f('tasks_user_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_user_id_fkey'), 'tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_user_id', table_name='tasks')
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.drop_column('tasks', 'parent_id')
    # ### end Alembic commands ###
