"""Add recurring_task_id to tasks table

Revision ID: 83c6bc227569
Revises: bf7c31d5b0f8
Create Date: 2025-11-03 18:26:31.039729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83c6bc227569'
down_revision: Union[str, Sequence[str], None] = 'bf7c31d5b0f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('recurring_task_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'recurring_tasks', ['recurring_task_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'recurring_task_id')
    # ### end Alembic commands ###
