"""Add manga table

Revision ID: b0aedba85e96
Revises: 735313b8c25e
Create Date: 2025-11-21 18:12:37.670978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0aedba85e96'
down_revision: Union[str, Sequence[str], None] = '735313b8c25e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manga',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='planned', nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('planned', 'in_progress', 'completed', 'dropped')", name='chk_manga_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_manga_completed', 'manga', ['user_id', 'completed_at'], unique=False)
    op.create_index('idx_manga_status', 'manga', ['user_id', 'status'], unique=False)
    op.create_index('idx_manga_title', 'manga', ['title'], unique=False)
    op.create_index('idx_manga_user', 'manga', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_manga_user', table_name='manga')
    op.drop_index('idx_manga_title', table_name='manga')
    op.drop_index('idx_manga_status', table_name='manga')
    op.drop_index('idx_manga_completed', table_name='manga')
    op.drop_table('manga')
    # ### end Alembic commands ###
