"""Add snooze_count field to tasks

Revision ID: bd61e0e0a838
Revises: 480b8f2a375c
Create Date: 2025-11-06 20:19:57.186018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd61e0e0a838'
down_revision: Union[str, Sequence[str], None] = '480b8f2a375c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('snooze_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'snooze_count')
    # ### end Alembic commands ###
