"""Add recurring tasks table

Revision ID: bf7c31d5b0f8
Revises: 4fa05d6bc550
Create Date: 2025-11-03 17:47:29.836632

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bf7c31d5b0f8'
down_revision: Union[str, Sequence[str], None] = '4fa05d6bc550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _ = op.create_table('recurring_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recurrence_type', sa.String(length=50), nullable=False),
    sa.Column('recurrence_days', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('recurrence_time', sa.Time(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('last_generated_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('priority_id', sa.Uuid(), nullable=True),
    sa.Column('label_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['priority_id'], ['priorities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recurring_tasks_is_active', 'recurring_tasks', ['is_active'], unique=False)
    op.create_index('ix_recurring_tasks_user_id', 'recurring_tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recurring_tasks_user_id', table_name='recurring_tasks')
    op.drop_index('ix_recurring_tasks_is_active', table_name='recurring_tasks')
    op.drop_table('recurring_tasks')
    # ### end Alembic commands ###
