"""Add anime table and anime_genres junction table

Revision ID: e4c4d30b6383
Revises: 6120c9c434eb
Create Date: 2025-11-22 13:30:30.250899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4c4d30b6383'
down_revision: Union[str, Sequence[str], None] = '6120c9c434eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='planned', nullable=False),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('planned', 'in_progress', 'completed', 'dropped')", name='chk_anime_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_anime_completed', 'anime', ['user_id', 'completed_at'], unique=False)
    op.create_index('idx_anime_status', 'anime', ['user_id', 'status'], unique=False)
    op.create_index('idx_anime_title', 'anime', ['title'], unique=False)
    op.create_index('idx_anime_user', 'anime', ['user_id'], unique=False)
    op.create_table('anime_genres',
    sa.Column('anime_id', sa.Uuid(), nullable=False),
    sa.Column('genre_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('anime_id', 'genre_id')
    )
    op.create_index('ix_anime_genres_anime_id', 'anime_genres', ['anime_id'], unique=False)
    op.create_index('ix_anime_genres_genre_id', 'anime_genres', ['genre_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_anime_genres_genre_id', table_name='anime_genres')
    op.drop_index('ix_anime_genres_anime_id', table_name='anime_genres')
    op.drop_table('anime_genres')
    op.drop_index('idx_anime_user', table_name='anime')
    op.drop_index('idx_anime_title', table_name='anime')
    op.drop_index('idx_anime_status', table_name='anime')
    op.drop_index('idx_anime_completed', table_name='anime')
    op.drop_table('anime')
    # ### end Alembic commands ###
