"""add note_links table for backlinks support

Revision ID: e8b6334e3e05
Revises: e4c4d30b6383
Create Date: 2025-11-22 19:22:35.276914

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e8b6334e3e05'
down_revision: Union[str, Sequence[str], None] = 'e4c4d30b6383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _ = op.create_table('note_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_note_id', sa.Uuid(), nullable=False),
    sa.Column('target_note_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_note_id', 'target_note_id', name='uq_note_link')
    )
    op.create_index('ix_note_links_source', 'note_links', ['source_note_id'], unique=False)
    op.create_index('ix_note_links_target', 'note_links', ['target_note_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_note_links_target', table_name='note_links')
    op.drop_index('ix_note_links_source', table_name='note_links')
    op.drop_table('note_links')
    # ### end Alembic commands ###
